$(document).ready(function () {
    $('#Products').DataTable();
});

$(document).ready(function () {
    $('#Category').DataTable();
        responsive:true
});

$(document).ready(function () {
    $('#Orders').DataTable();
});

$(document).ready(function () {
    $('#ORDERPEN').DataTable();
});

$(document).ready(function () {
    $('#ORDERUNC').DataTable();
});

$(document).ready(function () {
    $('#Papers').DataTable();
});

$(document).ready(function () {
    $('#Design').DataTable();
});

$(document).ready(function () {
    $('#Featured').DataTable();
});

$(document).ready(function () {
    $('#Template').DataTable();
});

$(document).ready(function () {
    $('#Users').DataTable();
});

$(document).ready(function () {
    $('#Client').DataTable();
});

$(document).ready(function () {
    $('#Employee').DataTable();
});

$(document).ready(function () {
    $('#Permision').DataTable();
});

$(document).ready(function () {
    $('#Roles').DataTable();
});

$(document).ready(function () {
    $('#CategoryType').DataTable();
});

$(document).ready(function () {
    $('#Size').DataTable();
});

$(document).ready(function () {
    $('#Quantity').DataTable();
});

$(document).ready(function () {
    $('#PaperT').DataTable();
});

$(document).ready(function () {
    $('#PaperSpecs').DataTable();
});

$(document).ready(function () {
    $('#PricingType').DataTable();
});

$(document).ready(function () {
    $('#Pricing').DataTable();
});






