






// const dropdownBtn1 = document.querySelector('.dropdown-Items')
// const submenu1 = document.querySelector('.submenu-Items')

// dropdownBtn1.addEventListener('click', function(e){
//     e.preventDefault();
//     submenu1.classList.toggle('Show');
// })


// const dropdownBtn3 = document.querySelector('.dropdown-Transactions')
// const submenu3 = document.querySelector('.submenu-Transactions')

// dropdownBtn3.addEventListener('click', function(e){
//     e.preventDefault();
//     submenu3.classList.toggle('Show');

// })




var dd_main = document.querySelector(".dd_main");

dd_main.addEventListener("click", function(){
this.classList.toggle("actives");
})